redis:
    redis_host: 127.0.0.1:6379
    redis_pwd:
mongoDb:
    #mongo_host: mongodb://admin:123456@127.0.0.1:27017
    mongo_host: mongodb://127.0.0.1:27017
    db_name: birdtalk
scyllaDb:
    scylla_host: 8.140.203.92:9042
    user: cassandra
    pwd: Tjj.31415
kafka:
    kafka_host:

server:
    host: 0.0.0.0
    port: 7817
    host_index: 1
    host_name: node1
    group_msg_queue_len: 100
    workers: 1
    schema: https
    cert: ./certs/cert.pem
    key: ./certs/key.pem
    friend_making: false
    cluster_mode: false
    avatar_font: ./ttf/SourceHanSans-VF.ttf
    file_base_path: e:/upload
    geolite2_path: ./resource/GeoLite2-City.mmdb
    log_level: debug
    token_key: 278b3e9f1c18f488314c7991e163c8bac880d5f09f4a15dc7589823dc6b43264


email:
    #tjj.31415
    smtp_addr: smtp.sina.com
    smtp_port: 25
    smtp_helo_host: sina.com
    user_name: birdchat@sina.com
    user_pwd: ee1a154926912af5
    tls_insecure_skip_verify: false
    auth_type: login
    workers: 3

